version: "3.8"

services:
  # auth_app:
  #   build: .
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
  #     JWT_SECRET: secret
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
